apiVersion: v1
kind: Service
metadata:
  name: notificator-backend
  labels:
    app: notificator-backend
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: notificator-backend