// proto/alert.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_UNKNOWN_UPDATE         UpdateType = 0
	UpdateType_COMMENT_ADDED          UpdateType = 1
	UpdateType_COMMENT_DELETED        UpdateType = 2
	UpdateType_ACKNOWLEDGMENT_ADDED   UpdateType = 3
	UpdateType_ACKNOWLEDGMENT_DELETED UpdateType = 4
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UNKNOWN_UPDATE",
		1: "COMMENT_ADDED",
		2: "COMMENT_DELETED",
		3: "ACKNOWLEDGMENT_ADDED",
		4: "ACKNOWLEDGMENT_DELETED",
	}
	UpdateType_value = map[string]int32{
		"UNKNOWN_UPDATE":         0,
		"COMMENT_ADDED":          1,
		"COMMENT_DELETED":        2,
		"ACKNOWLEDGMENT_ADDED":   3,
		"ACKNOWLEDGMENT_DELETED": 4,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_alert_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_proto_alert_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

// Comment Messages
type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AlertKey      string                 `protobuf:"bytes,2,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_proto_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AddCommentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddCommentRequest) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Comment       *Comment               `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_proto_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AddCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *AddCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertKey      string                 `protobuf:"bytes,1,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_proto_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommentsRequest) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_proto_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommentId     string                 `protobuf:"bytes,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_proto_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_proto_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlertKey      string                 `protobuf:"bytes,2,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_proto_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{6}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Acknowledgment Messages
type AddAcknowledgmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AlertKey      string                 `protobuf:"bytes,2,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAcknowledgmentRequest) Reset() {
	*x = AddAcknowledgmentRequest{}
	mi := &file_proto_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAcknowledgmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAcknowledgmentRequest) ProtoMessage() {}

func (x *AddAcknowledgmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAcknowledgmentRequest.ProtoReflect.Descriptor instead.
func (*AddAcknowledgmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{7}
}

func (x *AddAcknowledgmentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddAcknowledgmentRequest) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

func (x *AddAcknowledgmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddAcknowledgmentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Acknowledgment *Acknowledgment        `protobuf:"bytes,2,opt,name=acknowledgment,proto3" json:"acknowledgment,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddAcknowledgmentResponse) Reset() {
	*x = AddAcknowledgmentResponse{}
	mi := &file_proto_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAcknowledgmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAcknowledgmentResponse) ProtoMessage() {}

func (x *AddAcknowledgmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAcknowledgmentResponse.ProtoReflect.Descriptor instead.
func (*AddAcknowledgmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{8}
}

func (x *AddAcknowledgmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddAcknowledgmentResponse) GetAcknowledgment() *Acknowledgment {
	if x != nil {
		return x.Acknowledgment
	}
	return nil
}

func (x *AddAcknowledgmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAcknowledgmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertKey      string                 `protobuf:"bytes,1,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAcknowledgmentsRequest) Reset() {
	*x = GetAcknowledgmentsRequest{}
	mi := &file_proto_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcknowledgmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcknowledgmentsRequest) ProtoMessage() {}

func (x *GetAcknowledgmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcknowledgmentsRequest.ProtoReflect.Descriptor instead.
func (*GetAcknowledgmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{9}
}

func (x *GetAcknowledgmentsRequest) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

type GetAcknowledgmentsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Acknowledgments []*Acknowledgment      `protobuf:"bytes,1,rep,name=acknowledgments,proto3" json:"acknowledgments,omitempty"`
	Count           int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAcknowledgmentsResponse) Reset() {
	*x = GetAcknowledgmentsResponse{}
	mi := &file_proto_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAcknowledgmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcknowledgmentsResponse) ProtoMessage() {}

func (x *GetAcknowledgmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcknowledgmentsResponse.ProtoReflect.Descriptor instead.
func (*GetAcknowledgmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{10}
}

func (x *GetAcknowledgmentsResponse) GetAcknowledgments() []*Acknowledgment {
	if x != nil {
		return x.Acknowledgments
	}
	return nil
}

func (x *GetAcknowledgmentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteAcknowledgmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AlertKey      string                 `protobuf:"bytes,2,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAcknowledgmentRequest) Reset() {
	*x = DeleteAcknowledgmentRequest{}
	mi := &file_proto_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAcknowledgmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAcknowledgmentRequest) ProtoMessage() {}

func (x *DeleteAcknowledgmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAcknowledgmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAcknowledgmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAcknowledgmentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteAcknowledgmentRequest) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

type DeleteAcknowledgmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAcknowledgmentResponse) Reset() {
	*x = DeleteAcknowledgmentResponse{}
	mi := &file_proto_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAcknowledgmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAcknowledgmentResponse) ProtoMessage() {}

func (x *DeleteAcknowledgmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAcknowledgmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAcknowledgmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAcknowledgmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAcknowledgmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Acknowledgment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlertKey      string                 `protobuf:"bytes,2,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgment) Reset() {
	*x = Acknowledgment{}
	mi := &file_proto_alert_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgment) ProtoMessage() {}

func (x *Acknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgment.ProtoReflect.Descriptor instead.
func (*Acknowledgment) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{13}
}

func (x *Acknowledgment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Acknowledgment) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

func (x *Acknowledgment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Acknowledgment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Acknowledgment) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Acknowledgment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Real-time Updates Messages
type SubscribeToAlertUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AlertKey      string                 `protobuf:"bytes,2,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToAlertUpdatesRequest) Reset() {
	*x = SubscribeToAlertUpdatesRequest{}
	mi := &file_proto_alert_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToAlertUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToAlertUpdatesRequest) ProtoMessage() {}

func (x *SubscribeToAlertUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToAlertUpdatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToAlertUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeToAlertUpdatesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeToAlertUpdatesRequest) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

type AlertUpdate struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AlertKey   string                 `protobuf:"bytes,1,opt,name=alert_key,json=alertKey,proto3" json:"alert_key,omitempty"`
	UpdateType UpdateType             `protobuf:"varint,2,opt,name=update_type,json=updateType,proto3,enum=notificator.alert.UpdateType" json:"update_type,omitempty"`
	// Types that are valid to be assigned to UpdateData:
	//
	//	*AlertUpdate_Comment
	//	*AlertUpdate_Acknowledgment
	//	*AlertUpdate_DeletedCommentId
	//	*AlertUpdate_DeletedAcknowledgmentId
	UpdateData    isAlertUpdate_UpdateData `protobuf_oneof:"update_data"`
	Timestamp     *timestamppb.Timestamp   `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertUpdate) Reset() {
	*x = AlertUpdate{}
	mi := &file_proto_alert_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertUpdate) ProtoMessage() {}

func (x *AlertUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertUpdate.ProtoReflect.Descriptor instead.
func (*AlertUpdate) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{15}
}

func (x *AlertUpdate) GetAlertKey() string {
	if x != nil {
		return x.AlertKey
	}
	return ""
}

func (x *AlertUpdate) GetUpdateType() UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return UpdateType_UNKNOWN_UPDATE
}

func (x *AlertUpdate) GetUpdateData() isAlertUpdate_UpdateData {
	if x != nil {
		return x.UpdateData
	}
	return nil
}

func (x *AlertUpdate) GetComment() *Comment {
	if x != nil {
		if x, ok := x.UpdateData.(*AlertUpdate_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

func (x *AlertUpdate) GetAcknowledgment() *Acknowledgment {
	if x != nil {
		if x, ok := x.UpdateData.(*AlertUpdate_Acknowledgment); ok {
			return x.Acknowledgment
		}
	}
	return nil
}

func (x *AlertUpdate) GetDeletedCommentId() string {
	if x != nil {
		if x, ok := x.UpdateData.(*AlertUpdate_DeletedCommentId); ok {
			return x.DeletedCommentId
		}
	}
	return ""
}

func (x *AlertUpdate) GetDeletedAcknowledgmentId() string {
	if x != nil {
		if x, ok := x.UpdateData.(*AlertUpdate_DeletedAcknowledgmentId); ok {
			return x.DeletedAcknowledgmentId
		}
	}
	return ""
}

func (x *AlertUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isAlertUpdate_UpdateData interface {
	isAlertUpdate_UpdateData()
}

type AlertUpdate_Comment struct {
	Comment *Comment `protobuf:"bytes,3,opt,name=comment,proto3,oneof"`
}

type AlertUpdate_Acknowledgment struct {
	Acknowledgment *Acknowledgment `protobuf:"bytes,4,opt,name=acknowledgment,proto3,oneof"`
}

type AlertUpdate_DeletedCommentId struct {
	DeletedCommentId string `protobuf:"bytes,5,opt,name=deleted_comment_id,json=deletedCommentId,proto3,oneof"`
}

type AlertUpdate_DeletedAcknowledgmentId struct {
	DeletedAcknowledgmentId string `protobuf:"bytes,6,opt,name=deleted_acknowledgment_id,json=deletedAcknowledgmentId,proto3,oneof"`
}

func (*AlertUpdate_Comment) isAlertUpdate_UpdateData() {}

func (*AlertUpdate_Acknowledgment) isAlertUpdate_UpdateData() {}

func (*AlertUpdate_DeletedCommentId) isAlertUpdate_UpdateData() {}

func (*AlertUpdate_DeletedAcknowledgmentId) isAlertUpdate_UpdateData() {}

var File_proto_alert_proto protoreflect.FileDescriptor

const file_proto_alert_proto_rawDesc = "" +
	"\n" +
	"\x11proto/alert.proto\x12\x11notificator.alert\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x11AddCommentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\talert_key\x18\x02 \x01(\tR\balertKey\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"~\n" +
	"\x12AddCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x124\n" +
	"\acomment\x18\x02 \x01(\v2\x1a.notificator.alert.CommentR\acomment\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"1\n" +
	"\x12GetCommentsRequest\x12\x1b\n" +
	"\talert_key\x18\x01 \x01(\tR\balertKey\"c\n" +
	"\x13GetCommentsResponse\x126\n" +
	"\bcomments\x18\x01 \x03(\v2\x1a.notificator.alert.CommentR\bcomments\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"T\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\tR\tcommentId\"K\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\talert_key\x18\x02 \x01(\tR\balertKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\x18AddAcknowledgmentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\talert_key\x18\x02 \x01(\tR\balertKey\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9a\x01\n" +
	"\x19AddAcknowledgmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12I\n" +
	"\x0eacknowledgment\x18\x02 \x01(\v2!.notificator.alert.AcknowledgmentR\x0eacknowledgment\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"8\n" +
	"\x19GetAcknowledgmentsRequest\x12\x1b\n" +
	"\talert_key\x18\x01 \x01(\tR\balertKey\"\x7f\n" +
	"\x1aGetAcknowledgmentsResponse\x12K\n" +
	"\x0facknowledgments\x18\x01 \x03(\v2!.notificator.alert.AcknowledgmentR\x0facknowledgments\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"Y\n" +
	"\x1bDeleteAcknowledgmentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\talert_key\x18\x02 \x01(\tR\balertKey\"R\n" +
	"\x1cDeleteAcknowledgmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc5\x01\n" +
	"\x0eAcknowledgment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\talert_key\x18\x02 \x01(\tR\balertKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\\\n" +
	"\x1eSubscribeToAlertUpdatesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\talert_key\x18\x02 \x01(\tR\balertKey\"\xa6\x03\n" +
	"\vAlertUpdate\x12\x1b\n" +
	"\talert_key\x18\x01 \x01(\tR\balertKey\x12>\n" +
	"\vupdate_type\x18\x02 \x01(\x0e2\x1d.notificator.alert.UpdateTypeR\n" +
	"updateType\x126\n" +
	"\acomment\x18\x03 \x01(\v2\x1a.notificator.alert.CommentH\x00R\acomment\x12K\n" +
	"\x0eacknowledgment\x18\x04 \x01(\v2!.notificator.alert.AcknowledgmentH\x00R\x0eacknowledgment\x12.\n" +
	"\x12deleted_comment_id\x18\x05 \x01(\tH\x00R\x10deletedCommentId\x12<\n" +
	"\x19deleted_acknowledgment_id\x18\x06 \x01(\tH\x00R\x17deletedAcknowledgmentId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\r\n" +
	"\vupdate_data*~\n" +
	"\n" +
	"UpdateType\x12\x12\n" +
	"\x0eUNKNOWN_UPDATE\x10\x00\x12\x11\n" +
	"\rCOMMENT_ADDED\x10\x01\x12\x13\n" +
	"\x0fCOMMENT_DELETED\x10\x02\x12\x18\n" +
	"\x14ACKNOWLEDGMENT_ADDED\x10\x03\x12\x1a\n" +
	"\x16ACKNOWLEDGMENT_DELETED\x10\x042\xf7\x05\n" +
	"\fAlertService\x12Y\n" +
	"\n" +
	"AddComment\x12$.notificator.alert.AddCommentRequest\x1a%.notificator.alert.AddCommentResponse\x12\\\n" +
	"\vGetComments\x12%.notificator.alert.GetCommentsRequest\x1a&.notificator.alert.GetCommentsResponse\x12b\n" +
	"\rDeleteComment\x12'.notificator.alert.DeleteCommentRequest\x1a(.notificator.alert.DeleteCommentResponse\x12n\n" +
	"\x11AddAcknowledgment\x12+.notificator.alert.AddAcknowledgmentRequest\x1a,.notificator.alert.AddAcknowledgmentResponse\x12q\n" +
	"\x12GetAcknowledgments\x12,.notificator.alert.GetAcknowledgmentsRequest\x1a-.notificator.alert.GetAcknowledgmentsResponse\x12w\n" +
	"\x14DeleteAcknowledgment\x12..notificator.alert.DeleteAcknowledgmentRequest\x1a/.notificator.alert.DeleteAcknowledgmentResponse\x12n\n" +
	"\x17SubscribeToAlertUpdates\x121.notificator.alert.SubscribeToAlertUpdatesRequest\x1a\x1e.notificator.alert.AlertUpdate0\x01B*Z(notificator/internal/backend/proto/alertb\x06proto3"

var (
	file_proto_alert_proto_rawDescOnce sync.Once
	file_proto_alert_proto_rawDescData []byte
)

func file_proto_alert_proto_rawDescGZIP() []byte {
	file_proto_alert_proto_rawDescOnce.Do(func() {
		file_proto_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)))
	})
	return file_proto_alert_proto_rawDescData
}

var file_proto_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_alert_proto_goTypes = []any{
	(UpdateType)(0),                        // 0: notificator.alert.UpdateType
	(*AddCommentRequest)(nil),              // 1: notificator.alert.AddCommentRequest
	(*AddCommentResponse)(nil),             // 2: notificator.alert.AddCommentResponse
	(*GetCommentsRequest)(nil),             // 3: notificator.alert.GetCommentsRequest
	(*GetCommentsResponse)(nil),            // 4: notificator.alert.GetCommentsResponse
	(*DeleteCommentRequest)(nil),           // 5: notificator.alert.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),          // 6: notificator.alert.DeleteCommentResponse
	(*Comment)(nil),                        // 7: notificator.alert.Comment
	(*AddAcknowledgmentRequest)(nil),       // 8: notificator.alert.AddAcknowledgmentRequest
	(*AddAcknowledgmentResponse)(nil),      // 9: notificator.alert.AddAcknowledgmentResponse
	(*GetAcknowledgmentsRequest)(nil),      // 10: notificator.alert.GetAcknowledgmentsRequest
	(*GetAcknowledgmentsResponse)(nil),     // 11: notificator.alert.GetAcknowledgmentsResponse
	(*DeleteAcknowledgmentRequest)(nil),    // 12: notificator.alert.DeleteAcknowledgmentRequest
	(*DeleteAcknowledgmentResponse)(nil),   // 13: notificator.alert.DeleteAcknowledgmentResponse
	(*Acknowledgment)(nil),                 // 14: notificator.alert.Acknowledgment
	(*SubscribeToAlertUpdatesRequest)(nil), // 15: notificator.alert.SubscribeToAlertUpdatesRequest
	(*AlertUpdate)(nil),                    // 16: notificator.alert.AlertUpdate
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
}
var file_proto_alert_proto_depIdxs = []int32{
	7,  // 0: notificator.alert.AddCommentResponse.comment:type_name -> notificator.alert.Comment
	7,  // 1: notificator.alert.GetCommentsResponse.comments:type_name -> notificator.alert.Comment
	17, // 2: notificator.alert.Comment.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: notificator.alert.AddAcknowledgmentResponse.acknowledgment:type_name -> notificator.alert.Acknowledgment
	14, // 4: notificator.alert.GetAcknowledgmentsResponse.acknowledgments:type_name -> notificator.alert.Acknowledgment
	17, // 5: notificator.alert.Acknowledgment.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: notificator.alert.AlertUpdate.update_type:type_name -> notificator.alert.UpdateType
	7,  // 7: notificator.alert.AlertUpdate.comment:type_name -> notificator.alert.Comment
	14, // 8: notificator.alert.AlertUpdate.acknowledgment:type_name -> notificator.alert.Acknowledgment
	17, // 9: notificator.alert.AlertUpdate.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 10: notificator.alert.AlertService.AddComment:input_type -> notificator.alert.AddCommentRequest
	3,  // 11: notificator.alert.AlertService.GetComments:input_type -> notificator.alert.GetCommentsRequest
	5,  // 12: notificator.alert.AlertService.DeleteComment:input_type -> notificator.alert.DeleteCommentRequest
	8,  // 13: notificator.alert.AlertService.AddAcknowledgment:input_type -> notificator.alert.AddAcknowledgmentRequest
	10, // 14: notificator.alert.AlertService.GetAcknowledgments:input_type -> notificator.alert.GetAcknowledgmentsRequest
	12, // 15: notificator.alert.AlertService.DeleteAcknowledgment:input_type -> notificator.alert.DeleteAcknowledgmentRequest
	15, // 16: notificator.alert.AlertService.SubscribeToAlertUpdates:input_type -> notificator.alert.SubscribeToAlertUpdatesRequest
	2,  // 17: notificator.alert.AlertService.AddComment:output_type -> notificator.alert.AddCommentResponse
	4,  // 18: notificator.alert.AlertService.GetComments:output_type -> notificator.alert.GetCommentsResponse
	6,  // 19: notificator.alert.AlertService.DeleteComment:output_type -> notificator.alert.DeleteCommentResponse
	9,  // 20: notificator.alert.AlertService.AddAcknowledgment:output_type -> notificator.alert.AddAcknowledgmentResponse
	11, // 21: notificator.alert.AlertService.GetAcknowledgments:output_type -> notificator.alert.GetAcknowledgmentsResponse
	13, // 22: notificator.alert.AlertService.DeleteAcknowledgment:output_type -> notificator.alert.DeleteAcknowledgmentResponse
	16, // 23: notificator.alert.AlertService.SubscribeToAlertUpdates:output_type -> notificator.alert.AlertUpdate
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_alert_proto_init() }
func file_proto_alert_proto_init() {
	if File_proto_alert_proto != nil {
		return
	}
	file_proto_alert_proto_msgTypes[15].OneofWrappers = []any{
		(*AlertUpdate_Comment)(nil),
		(*AlertUpdate_Acknowledgment)(nil),
		(*AlertUpdate_DeletedCommentId)(nil),
		(*AlertUpdate_DeletedAcknowledgmentId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alert_proto_rawDesc), len(file_proto_alert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alert_proto_goTypes,
		DependencyIndexes: file_proto_alert_proto_depIdxs,
		EnumInfos:         file_proto_alert_proto_enumTypes,
		MessageInfos:      file_proto_alert_proto_msgTypes,
	}.Build()
	File_proto_alert_proto = out.File
	file_proto_alert_proto_goTypes = nil
	file_proto_alert_proto_depIdxs = nil
}
