# Default values for notificator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []

# Backend service configuration
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: soulkyu/notificator-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  service:
    type: ClusterIP
    grpcPort: 50051
    httpPort: 8080
  ingress:
    enabled: false
    className: "nginx"
    annotations:
      # Required for gRPC support
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      # Optional: Enable gRPC-Web if needed for browser clients
      # nginx.ingress.kubernetes.io/grpc-backend: "true"
    hosts:
      - host: notificator-backend.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: notificator-backend-tls
    #    hosts:
    #      - notificator-backend.example.com
  # Database configuration
  database:
    # Type of database: sqlite or postgres
    type: postgres
    # SQLite configuration (if type is sqlite)
    sqlite:
      # Path to SQLite database file (in persistent volume)
      path: "/data/notificator.db"
    # PostgreSQL configuration (if type is postgres)
    postgres:
      host: "postgres-service"
      port: 5432
      database: "notificator"
      user: "notificator"
      # Password should be provided via existingSecret
      password: ""
      sslMode: "disable"
      # Use existing secret for database credentials
      existingSecret: ""
      # Keys in the secret
      secretKeys:
        password: "postgres-password"
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

# WebUI service configuration  
webui:
  enabled: true
  replicaCount: 1
  image:
    repository: soulkyu/notificator-webui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: notificator.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  
# Optional Alertmanager (for testing/development)
alertmanager:
  enabled: false
  replicaCount: 1
  image:
    repository: soulkyu/notificator-alertmanager  
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 9093
  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts:
      - host: alertmanager.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


nodeSelector: {}

tolerations: []

affinity: {}


# Persistence configuration for SQLite
persistence:
  enabled: true
  # Only used when database type is sqlite
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  # existingClaim: ""

# Additional environment variables
env: []
  # - name: LOG_LEVEL
  #   value: "debug"

# Additional environment variables from secrets
envFrom: []
  # - secretRef:
  #     name: notificator-backend-secrets