# Example values for production deployment
# Copy this file and modify according to your needs

# Container image settings
image:
  repository: your-registry/notificator-backend
  tag: "latest"
  pullPolicy: Always

# Enable ingress with gRPC support
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
  hosts:
    - host: notificator-backend.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: notificator-backend-tls
      hosts:
        - notificator-backend.example.com

# PostgreSQL database configuration
backend:
  database:
    type: postgres
    postgres:
      host: "postgres.database.svc.cluster.local"
      port: 5432
      database: "notificator"
      user: "notificator"
      existingSecret: "postgres-credentials"
      secretKeys:
        password: "postgres-password"

# Resource limits for production
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Enable autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Node placement
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - notificator-backend
          topologyKey: kubernetes.io/hostname