// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BackendWarning() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"backend-warning\" x-data=\"backendStatus()\" x-init=\"checkBackend()\" x-show=\"!isConnected\" class=\"bg-red-500 text-gray-900 dark:text-white p-3 mb-4 text-center\"><p class=\"text-sm font-medium\">⚠️ Backend is unavailable - Trying to connect to localhost:50051</p></div><script>\n\t\tfunction backendStatus() {\n\t\t\treturn {\n\t\t\t\tisConnected: true, // Assume connected initially to avoid flash\n\t\t\t\tchecking: false,\n\t\t\t\t\n\t\t\t\tasync checkBackend() {\n\t\t\t\t\tthis.checking = true;\n\t\t\t\t\ttry {\n\t\t\t\t\t\tconst response = await fetch('/health/backend');\n\t\t\t\t\t\tthis.isConnected = response.ok;\n\t\t\t\t\t} catch (error) {\n\t\t\t\t\t\tthis.isConnected = false;\n\t\t\t\t\t} finally {\n\t\t\t\t\t\tthis.checking = false;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
