{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: notificator-alertmanager
  labels:
    app: notificator-alertmanager
    {{- with .Values.alertmanager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.alertmanager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: notificator-alertmanager
{{- end }}