apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificator-backend
  labels:
    app: notificator-backend
    {{- with .Values.backend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificator-backend
  template:
    metadata:
      labels:
        app: notificator-backend
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "notificator.backend.serviceAccountName" . }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command:
        - ./notificator-backend
        - backend
        - --config
        - /config/config.json
        ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- with .Values.backend.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        {{- if .Values.backend.database.postgresUrl }}
        - name: POSTGRES_URL
          value: {{ .Values.backend.database.postgresUrl | quote }}
        {{- else if eq .Values.backend.database.type "postgres" }}
        - name: DB_HOST
          value: {{ .Values.backend.database.postgres.host | quote }}
        - name: DB_PORT
          value: {{ .Values.backend.database.postgres.port | quote }}
        - name: DB_NAME
          value: {{ .Values.backend.database.postgres.database | quote }}
        - name: DB_USER
          value: {{ .Values.backend.database.postgres.user | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.backend.database.postgres.password | quote }}
        - name: DB_SSL_MODE
          value: {{ .Values.backend.database.postgres.sslMode | quote }}
        {{- else if eq .Values.backend.database.type "sqlite" }}
        - name: DB_PATH
          value: {{ .Values.backend.database.sqlite.path | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: notificator-backend-config-json