apiVersion: v1
kind: Service
metadata:
  name: notificator-backend
  labels:
    app: notificator-backend
    {{- with .Values.backend.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: notificator-backend