apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificator-backend
  labels:
    app: notificator-backend
    {{- with .Values.backend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificator-backend
  template:
    metadata:
      labels:
        app: notificator-backend
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "notificator.backend.serviceAccountName" . }}
      {{- with .Values.backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command:
        - ./notificator-backend
        - backend
        ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- with .Values.backend.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        # Custom environment variables from values.yaml
        {{- range $key, $value := .Values.backend.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        
        # Global settings (can be overridden by backend.env)
        {{- if not (hasKey .Values.backend.env "NOTIFICATOR_LOG_LEVEL") }}
        - name: NOTIFICATOR_LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        {{- end }}
        {{- if not (hasKey .Values.backend.env "NOTIFICATOR_WEBUI_PLAYGROUND") }}
        - name: NOTIFICATOR_WEBUI_PLAYGROUND
          value: {{ .Values.playground | quote }}
        {{- end }}
        
        # Alertmanager configuration (can be overridden by backend.env)
        {{- $index := 0 }}
        {{- if .Values.alertmanager.enabled }}
        {{- $nameKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_NAME" $index }}
        {{- $urlKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_URL" $index }}
        {{- if not (hasKey $.Values.backend.env $nameKey) }}
        - name: {{ $nameKey }}
          value: "Internal Alertmanager"
        {{- end }}
        {{- if not (hasKey $.Values.backend.env $urlKey) }}
        - name: {{ $urlKey }}
          value: "http://notificator-alertmanager:9093"
        {{- end }}
        {{- $oauthProxyKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_OAUTH_PROXY_MODE" $index }}
        {{- if not (hasKey $.Values.backend.env $oauthProxyKey) }}
        - name: {{ $oauthProxyKey }}
          value: "true"
        {{- end }}
        {{- $index = add $index 1 }}
        {{- end }}
        {{- range $am := .Values.alertmanagerConfig }}
        {{- $nameKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_NAME" $index }}
        {{- $urlKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_URL" $index }}
        {{- if not (hasKey $.Values.backend.env $nameKey) }}
        - name: {{ $nameKey }}
          value: {{ $am.name | quote }}
        {{- end }}
        {{- if not (hasKey $.Values.backend.env $urlKey) }}
        - name: {{ $urlKey }}
          value: {{ $am.url | quote }}
        {{- end }}
        {{- if $am.username }}
        {{- $usernameKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_USERNAME" $index }}
        {{- if not (hasKey $.Values.backend.env $usernameKey) }}
        - name: {{ $usernameKey }}
          value: {{ $am.username | quote }}
        {{- end }}
        {{- end }}
        {{- if $am.password }}
        {{- $passwordKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_PASSWORD" $index }}
        {{- if not (hasKey $.Values.backend.env $passwordKey) }}
        - name: {{ $passwordKey }}
          value: {{ $am.password | quote }}
        {{- end }}
        {{- end }}
        {{- if $am.token }}
        {{- $tokenKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_TOKEN" $index }}
        {{- if not (hasKey $.Values.backend.env $tokenKey) }}
        - name: {{ $tokenKey }}
          value: {{ $am.token | quote }}
        {{- end }}
        {{- end }}
        {{- if $am.oauthEnabled }}
        {{- $oauthEnabledKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_OAUTH_ENABLED" $index }}
        {{- $oauthProxyKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_OAUTH_PROXY_MODE" $index }}
        {{- if not (hasKey $.Values.backend.env $oauthEnabledKey) }}
        - name: {{ $oauthEnabledKey }}
          value: {{ $am.oauthEnabled | quote }}
        {{- end }}
        {{- if not (hasKey $.Values.backend.env $oauthProxyKey) }}
        - name: {{ $oauthProxyKey }}
          value: {{ $am.oauthProxyMode | default true | quote }}
        {{- end }}
        {{- end }}
        {{- $index = add $index 1 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi