apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificator-webui
  labels:
    app: notificator-webui
    {{- with .Values.webui.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificator-webui
  template:
    metadata:
      labels:
        app: notificator-webui
        {{- with .Values.webui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.webui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "notificator.webui.serviceAccountName" . }}
      {{- with .Values.webui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: webui
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
        imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
        command:
        - ./webui
        - webui
        - --backend
        - {{ .Values.webui.backendAddress }}
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        {{- with .Values.webui.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        # Backend connection
        - name: BACKEND_ADDRESS
          value: {{ .Values.webui.backendAddress | quote }}
        - name: NOTIFICATOR_WEBUI_LISTEN
          value: ":8081"
        - name: NOTIFICATOR_WEBUI_BACKEND
          value: {{ .Values.webui.backendAddress | quote }}
        - name: NOTIFICATOR_WEBUI_PLAYGROUND
          value: {{ .Values.playground | quote }}
        
        # Alertmanager configuration
        {{- $alertmanagers := include "notificator.allAlertmanagers" . | fromJson }}
        {{- range $index, $am := $alertmanagers }}
        - name: NOTIFICATOR_ALERTMANAGERS_{{ $index }}_NAME
          value: {{ $am.name | quote }}
        - name: NOTIFICATOR_ALERTMANAGERS_{{ $index }}_URL
          value: {{ $am.url | quote }}
        {{- if $am.oauthEnabled }}
        - name: NOTIFICATOR_ALERTMANAGERS_{{ $index }}_OAUTH_ENABLED
          value: {{ $am.oauthEnabled | quote }}
        - name: NOTIFICATOR_ALERTMANAGERS_{{ $index }}_OAUTH_PROXY_MODE
          value: {{ $am.oauthProxyMode | default true | quote }}
        {{- end }}
        {{- end }}
        
        # Logging
        - name: NOTIFICATOR_LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi