apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificator-webui
  labels:
    app: notificator-webui
    {{- with .Values.webui.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificator-webui
  template:
    metadata:
      labels:
        app: notificator-webui
        {{- with .Values.webui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.webui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "notificator.webui.serviceAccountName" . }}
      {{- with .Values.webui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: webui
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
        imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
        command:
        - ./webui
        - webui
        - --backend
        - {{ .Values.webui.backendAddress }}
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        {{- with .Values.webui.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        # Custom environment variables from values.yaml
        {{- range $key, $value := .Values.webui.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        
        # Backend connection (can be overridden by webui.env)
        {{- if not (hasKey .Values.webui.env "BACKEND_ADDRESS") }}
        - name: BACKEND_ADDRESS
          value: {{ .Values.webui.backendAddress | quote }}
        {{- end }}
        {{- if not (hasKey .Values.webui.env "NOTIFICATOR_WEBUI_BACKEND") }}
        - name: NOTIFICATOR_WEBUI_BACKEND
          value: {{ .Values.webui.backendAddress | quote }}
        {{- end }}
        {{- if not (hasKey .Values.webui.env "NOTIFICATOR_WEBUI_LISTEN") }}
        - name: NOTIFICATOR_WEBUI_LISTEN
          value: ":8081"
        {{- end }}
        
        # Global settings (can be overridden by webui.env)
        {{- if not (hasKey .Values.webui.env "NOTIFICATOR_LOG_LEVEL") }}
        - name: NOTIFICATOR_LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        {{- end }}
        {{- if not (hasKey .Values.webui.env "NOTIFICATOR_WEBUI_PLAYGROUND") }}
        - name: NOTIFICATOR_WEBUI_PLAYGROUND
          value: {{ .Values.playground | quote }}
        {{- end }}
        
        # Alertmanager configuration (can be overridden by webui.env)
        {{- $index := 0 }}
        {{- if .Values.alertmanager.enabled }}
        {{- $nameKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_NAME" $index }}
        {{- $urlKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_URL" $index }}
        {{- if not (hasKey $.Values.webui.env $nameKey) }}
        - name: {{ $nameKey }}
          value: "Internal Alertmanager"
        {{- end }}
        {{- if not (hasKey $.Values.webui.env $urlKey) }}
        - name: {{ $urlKey }}
          value: "http://notificator-alertmanager:9093"
        {{- end }}
        {{- $oauthProxyKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_OAUTH_PROXY_MODE" $index }}
        {{- if not (hasKey $.Values.webui.env $oauthProxyKey) }}
        - name: {{ $oauthProxyKey }}
          value: "true"
        {{- end }}
        {{- $index = add $index 1 }}
        {{- end }}
        {{- range $am := .Values.alertmanagerConfig }}
        {{- $nameKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_NAME" $index }}
        {{- $urlKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_URL" $index }}
        {{- if not (hasKey $.Values.webui.env $nameKey) }}
        - name: {{ $nameKey }}
          value: {{ $am.name | quote }}
        {{- end }}
        {{- if not (hasKey $.Values.webui.env $urlKey) }}
        - name: {{ $urlKey }}
          value: {{ $am.url | quote }}
        {{- end }}
        {{- if $am.oauthEnabled }}
        {{- $oauthEnabledKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_OAUTH_ENABLED" $index }}
        {{- $oauthProxyKey := printf "NOTIFICATOR_ALERTMANAGERS_%d_OAUTH_PROXY_MODE" $index }}
        {{- if not (hasKey $.Values.webui.env $oauthEnabledKey) }}
        - name: {{ $oauthEnabledKey }}
          value: {{ $am.oauthEnabled | quote }}
        {{- end }}
        {{- if not (hasKey $.Values.webui.env $oauthProxyKey) }}
        - name: {{ $oauthProxyKey }}
          value: {{ $am.oauthProxyMode | default true | quote }}
        {{- end }}
        {{- end }}
        {{- $index = add $index 1 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi