apiVersion: v1
kind: Service
metadata:
  name: notificator-webui
  labels:
    app: notificator-webui
    {{- with .Values.webui.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.webui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: notificator-webui