apiVersion: v1
kind: Service
metadata:
  name: notificator-webui
  labels:
    app: notificator-webui
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: notificator-webui