apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notificator-backend.fullname" . }}
  labels:
    {{- include "notificator-backend.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "alertmanagers": [],
      "gui": {
        "width": 1920,
        "height": 1080,
        "title": "Notificator - Alert Dashboard"
      },
      "notifications": {
        "enabled": false
      },
      "polling": {
        "interval": 30000000000
      },
      "backend": {
        "enabled": true,
        "grpc_listen": ":50051",
        "grpc_client": "localhost:50051",
        "http_listen": ":8080",
        "database": {
          {{- if eq .Values.backend.database.type "sqlite" }}
          "type": "sqlite",
          "sqlite_path": "{{ .Values.backend.database.sqlite.path }}"
          {{- else if eq .Values.backend.database.type "postgres" }}
          "type": "postgres",
          "host": "{{ .Values.backend.database.postgres.host }}",
          "port": {{ .Values.backend.database.postgres.port }},
          "name": "{{ .Values.backend.database.postgres.database }}",
          "user": "{{ .Values.backend.database.postgres.user }}",
          {{- if .Values.backend.database.postgres.existingSecret }}
          "password": "{{ printf "${POSTGRES_PASSWORD}" }}",
          {{- else }}
          "password": "{{ .Values.backend.database.postgres.password }}",
          {{- end }}
          "ssl_mode": "{{ .Values.backend.database.postgres.sslMode }}"
          {{- end }}
        }
      }
    }