{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notificator-backend.fullname" . }}
  labels:
    {{- include "notificator-backend.labels" . | nindent 4 }}
data:
  config.json: |
    {{- $config := deepCopy .Values.backend.config }}
    {{- $dbConfig := dict }}
    {{- if eq .Values.backend.database.type "sqlite" }}
    {{- $_ := set $dbConfig "type" "sqlite" }}
    {{- $_ := set $dbConfig "sqlite_path" .Values.backend.database.sqlite.path }}
    {{- else if eq .Values.backend.database.type "postgres" }}
    {{- $_ := set $dbConfig "type" "postgres" }}
    {{- $_ := set $dbConfig "host" .Values.backend.database.postgres.host }}
    {{- $_ := set $dbConfig "port" .Values.backend.database.postgres.port }}
    {{- $_ := set $dbConfig "name" .Values.backend.database.postgres.database }}
    {{- $_ := set $dbConfig "user" .Values.backend.database.postgres.user }}
    {{- if .Values.backend.database.postgres.existingSecret }}
    {{- $_ := set $dbConfig "password" "${POSTGRES_PASSWORD}" }}
    {{- else }}
    {{- $_ := set $dbConfig "password" .Values.backend.database.postgres.password }}
    {{- end }}
    {{- $_ := set $dbConfig "ssl_mode" .Values.backend.database.postgres.sslMode }}
    {{- end }}
    {{- $_ := set $config.backend "database" $dbConfig }}
    {{- $config | toJson | nindent 4 }}
{{- end }}