{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notificator-backend.fullname" . }}-webui
  labels:
    {{- include "notificator-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  {{- if not .Values.webui.autoscaling.enabled }}
  replicas: {{ .Values.webui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "notificator-backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "notificator-backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "notificator-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: webui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          command:
            - /notificator-webui
            - webui
            - --backend-addr
            - {{ include "notificator-backend.fullname" . }}:{{ .Values.backend.service.grpcPort }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}